/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion_pierre (void);
GtkWidget* create_admin_pierre (void);
GtkWidget* create_Gestion_election_pierre (void);
GtkWidget* create_Ajout_election_pierre (void);
GtkWidget* create_Modifier_election_pierre (void);
GtkWidget* create_Supprimer_election_pierre (void);
GtkWidget* create_Ajout_bureaux_Omar (void);
GtkWidget* create_Modifier_bureaux_Omar (void);
GtkWidget* create_Agent_bureau_vote_Omar (void);
GtkWidget* create_Gestion_bureaux_vote_Omar (void);
GtkWidget* create_Suppression_bureau_vote_Omar (void);
GtkWidget* create_Gestion_user_Ramadan (void);
GtkWidget* create_Ajout_utilisateur_Ramadan (void);
GtkWidget* create_Modifier_users_Ramadan (void);
GtkWidget* create_Supprimer_utilisateur_Ramadan (void);
GtkWidget* create_Ajout_reclalmation_Majdi (void);
GtkWidget* create_Modifier_reclamation_Majdi (void);
GtkWidget* create_SUpprimer_reclamation_Majdi (void);
GtkWidget* create_Gestion_reclamation_Majdi (void);
GtkWidget* create_Gestion_liste_electorale_Aziz (void);
GtkWidget* create_AJout_liste_electorale_Aziz (void);
GtkWidget* create_Modifier_liste_electorale_Aziz (void);
GtkWidget* create_Supprimer_liste_electorale_Aziz (void);
GtkWidget* create_Statistique (void);
